# Functions for Multifractal analysis 


# Plot a sed file
#
# fname: file name
# gname: graph title 
# dX: range in columns to plot
# col: vector of colors to make the color palette
# shf: shift in the vector of colors 
#
plot_sed_image <- function(fname,gname,dX=0,col=0,shf=0)
  {
  require(lattice)
  require(RColorBrewer)
  per <-data.matrix(read.table(fname, skip=2,header=F))
  if(length(dX)>1) per <- per[,dX]
  mp = max(per)
  if(mp<50) {
    mp = 50
    seqat = seq( min(per),max(per),(max(per)-min(per))/50)
  }
  else
  {
    seqat = seq( min(per),mp,5)
  }
  if(length(col)==1) col.l <- colorRampPalette(c('white', 'green', 'purple', 'yellow', 'brown'))(mp) 
  else col.l <- colorRampPalette(col)(mp) 
  if( shf>0) col.l = col.l[shf:mp]
  levelplot(per, scales = list(draw = FALSE),xlab =NULL, ylab = NULL,col.regions=col.l,
            useRaster=T,at=seqat,
            main=list( gname,cex=1))
  }

# Read a sed file in a matrix
#
# fname: file name of the sed file
#
read_sed <- function(fname)
{
  per <-data.matrix(read.table(fname, skip=2,header=F))
}

# Calculates the multifractal spectrum and 
# put the result in a frame
# 
# fname: file name of the input file
# parms: parameters for mfSBA
# recalc: FALSE = if the output file exist read it don't calculate Dq again
#         TRUE  = always calculate Dq
#
calcDq_mfSBA <- function(fname,parms,recalc=FALSE)
  {
  sname <- paste0("s.", fname)
  if((!file.exists(sname)) | recalc)
    {
    syst.txt <- paste("./mfSBA ",fname, parms)
    system(syst.txt)
    }
  pp <- read.delim(sname, header=T)
  
  for(nc in 1:ncol(pp)){
    if( class(pp[,nc ])=="factor") pp[,nc]<-as.numeric(as.character(pp[,nc])) 
  }
  
  pp$Dq  <- with(pp,ifelse(q==1,alfa,Tau/(q-1)))
  pp$SD.Dq  <- with(pp,ifelse(q==1,SD.alfa,abs(SD.Tau/(q-1))))
  pp$R.Dq <- with(pp,ifelse(q==1,R.alfa,R.Tau))
  return(pp[,c("q","Dq","SD.Dq","R.Dq")])
  }


# Calculates the multifractal spectrum of a multispecies 2D distribution
# and put the result in a frame
# 
# fname: file name of the input file
# parms: parameters for mfSBA
# recalc: FALSE = if the output file exist read it don't calculate Dq again
#         TRUE  = always calculate Dq
#

calcDq_multiSBA <- function(fname,parms,recalc=FALSE)
{
  sname <- paste0("s.", fname)
  if((!file.exists(sname)) | recalc)
  {
    syst.txt <- paste("./multiSpeciesSBA ",fname, parms)
    system(syst.txt)
  }
  pp <- read.delim(sname, header=T)
  
  for(nc in 1:ncol(pp)){
    if( class(pp[,nc ])=="factor") pp[,nc]<-as.numeric(as.character(pp[,nc])) 
  }
  
  pp$Dq  <- with(pp,ifelse(q==1,alfa,Tau/(q-1)))
  pp$SD.Dq  <- with(pp,ifelse(q==1,SD.alfa,abs(SD.Tau/(q-1))))
  pp$R.Dq <- with(pp,ifelse(q==1,R.alfa,R.Tau))
  return(pp[,c("q","Dq","SD.Dq","R.Dq")])
}

# Calc mfSBA
# draw histogram
# add to a dataframe dq with a new variable site = siten
#
addDqRHist <- function(fname,dq=0,siten="")
{
  # Extract site label
  if( nchar(siten)==0 ){  
    siten <- strsplit(fname,".sed")[[1]][1]
  }
  
  # Make multifractal analysis
  
  dqnew <- calcDq_mfSBA(fname)
  dqnew$Site <- siten
  
  #require(ggplot2)
  #print(ggplot(dqnew, aes(x=R.Dq)) + geom_histogram() + ggtitle(siten))
  hist(dqnew$R.Dq)
  if(is.data.frame(dq))
    return(rbind(dq,dqnew))
  else
    return(dqnew)
}

# Function to graph multifractal spectra with CI
#
# El error dinnames es que no todas las variables son numéricas
# Usa Type como variable de grupo y LowCI,HighCI para el CI
#
plot_DqCI <- function(DqCI, tit="Type")
  {
  require(lattice)
  require(Hmisc)
  LowCI <- with(DqCI,Dq-SD.Dq)
  HighCI <-with(DqCI,Dq+SD.Dq)
  with(DqCI,
    xYplot(Cbind(Dq,Dq-SD.Dq,Dq+SD.Dq) ~ q, data=DqCI, nx=FALSE, groups=Site, type="l",
           scales=list(tck=-1),
           cap=.01,
           ylim=c(min(LowCI)-.01,max(HighCI)+.01),
    	     panel=function(...){
  		     panel.abline(h=2, col="grey", lty=2)
  		     panel.xYplot(...)},
  		     ylab=expression(italic(D[q])),
  		     xlab=expression(italic(q)),
           label.curves=F,
           auto.key=list(x=.60,y=.9,title=tit,cex.title=.9, lines=T,points=F,cex=.7),
           )
       )
  }


# Function to plot Dq fit from t* files generated by mfSBA 
# 
# fname: file name of the t.inputFile
# qname: file name of the q sed file used
#
plotDqFit <- function(fname,qname)
{
  zq <- read.table(fname, sep="\t",header=T)
  cna <- read_sed(qname)
  q <-t(cna)
  zq0 <- reshape(zq, timevar="q",times=q,v.names=c("logTr"),
                 varying=list(3:length(names(zq))),
                 direction="long")
  library(lattice)
  zq1 <- subset(zq0, q==1 | q==2 | q==3 | q==4 | q==5 | q==0 | q==-1 | q==-2 | q==-3 | q==-4 | q==-5 )

#  oname <- paste("lsaravia_figS_W",sem,"_",wnro,".tif",sep="")
#  tiff(oname, width=4.86,height=4.86,units="in",res=600,compression=c("lzw"))
  
  trellis.par.set(superpose.symbol=list(pch=c(0,1,2,3,4,5,6,8,15,16,17)))
  trellis.par.set(superpose.symbol=list(cex=c(rep(0.6,11))))
  trellis.par.set(superpose.line=list(lty=3))
  
  #show.settings()
  if(names(zq1)[2]=="LogBox") names(zq1)[2]<-"Log.Box"
  print(xyplot(logTr~Log.Box , data =zq1, groups=q, type=c("r","p"), scales=list(tck=-1), 
               #main=list(wtitle,cex=0.9),
               auto.key=list(space = "right",title=expression(italic("q")),cex.title=.7, points=TRUE,cex=.7),
               ylab=expression(italic(paste("log ",  Z[q](epsilon) ))) , xlab=expression(italic(paste("log ",epsilon)))  
  ))
#  dev.off()    
}


# Save a matrix as a sed file with type BI (floating point)
#
save_matrix_as_sed <- function(mat,fname)
{
  header <- paste(nrow(mat),ncol(mat),"BI")
  write.table(header,file=fname,row.names=F,col.names=F,quote=F)
  write.table(mat,file=fname,row.names=F,col.names=F,quote=F,append=T)
}
